# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DMAgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 556)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(420, 50, 221, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.SFR = QtWidgets.QLCDNumber(self.centralwidget)
        self.SFR.setGeometry(QtCore.QRect(530, 180, 111, 61))
        self.SFR.setObjectName("SFR")
        self.HV = QtWidgets.QLCDNumber(self.centralwidget)
        self.HV.setGeometry(QtCore.QRect(530, 250, 111, 61))
        self.HV.setObjectName("HV")
        self.AFR = QtWidgets.QLCDNumber(self.centralwidget)
        self.AFR.setGeometry(QtCore.QRect(530, 110, 111, 61))
        self.AFR.setObjectName("AFR")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 120, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 190, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 260, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.MonitorFrame = QtWidgets.QFrame(self.centralwidget)
        self.MonitorFrame.setGeometry(QtCore.QRect(390, 30, 291, 321))
        self.MonitorFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.MonitorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MonitorFrame.setLineWidth(3)
        self.MonitorFrame.setObjectName("MonitorFrame")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(70, 50, 221, 51))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.HVsettxt = QtWidgets.QTextEdit(self.centralwidget)
        self.HVsettxt.setGeometry(QtCore.QRect(160, 110, 131, 41))
        self.HVsettxt.setObjectName("HVsettxt")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 170, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.SFRSETtxt = QtWidgets.QTextEdit(self.centralwidget)
        self.SFRSETtxt.setGeometry(QtCore.QRect(160, 170, 131, 41))
        self.SFRSETtxt.setObjectName("SFRSETtxt")
        self.MonitorFrame_2 = QtWidgets.QFrame(self.centralwidget)
        self.MonitorFrame_2.setGeometry(QtCore.QRect(40, 30, 291, 211))
        self.MonitorFrame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.MonitorFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MonitorFrame_2.setLineWidth(3)
        self.MonitorFrame_2.setObjectName("MonitorFrame_2")
        self.MonitorFrame_2.raise_()
        self.MonitorFrame.raise_()
        self.textBrowser.raise_()
        self.SFR.raise_()
        self.HV.raise_()
        self.AFR.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.textBrowser_2.raise_()
        self.HVsettxt.raise_()
        self.label_5.raise_()
        self.SFRSETtxt.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Monitor</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Aerosol FR"))
        self.label_2.setText(_translate("MainWindow", "Sheath FR"))
        self.label_3.setText(_translate("MainWindow", "High Voltage"))
        self.label_4.setText(_translate("MainWindow", "HV Set"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Selection</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "SFR Set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
